# Use a base image suitable for your Python application
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy your application code and requirements to the container
COPY service2/requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the rest of the application files
COPY service2 /app

# Specify the command to start your service
CMD ["python", "app.py"]

